apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCPN4vuQpJWekZ1bIMJi9eXGnaC67SkX3jG58XfwjykO3GD++rf3lwMvP3oZbBe+gOHBdpuNNn5m8nLnTLVVhrhqmgM+W0WVv7ZZNF8pJLwBtl5tBCcF/qXYCESPD5Dp0kTZGZ6BJtxz4+yinCqZ22oKhM7uhxo7nn5HlVN1SggUE9535sq8GMSIESI/yEboEWp4lREBusPpD79FuFaX7e6gSpWyekdMInVKr46EPNQSqAvzGtf2DBd/3IasN6J1EGQgvz1JQPBPfz9m95Ng/kpUjEjDVXux3seCBTWG1MYHDUmRYTE0OwyvwKq1iyUYu8Zttihgt6z7dtXX+f0jpVmgDjyjIFo3jNgjUCEhYPNFklH9RqRS+GUsHi5qlM9vr1qvCmxkOugKabheCrAhW1mYDGpNX4o10+Khss4Z93NWiKa12mRrnMkpyWplTqn4ytUaY+bGqoF7HpP0BITm9iza6TQF8CBF8CtE4cVC4RulWPJ2qtb+lXOOnjwPz6PS6whc6CvoBusQaA3oN1Qj1Hne+rvAZbXlDJmAyFoQDPZP1KdxzVpOO+SAki4d/kuAC+y5900oREuEAcjjFdv7EYL2EXqaCfFqtRT8T/Ta2cq5rKzwK/gSbVc1+8L8QgN/yfoihARAVFy0zW5H+FGMo4hrgbxwA9MSVt22oOdb7ad644yDL5DYceQLEafiad+6dJc8s2v8bM20WM4d2w=
    username: AgBUDcL+RyCWY7Y5i+/BlpFuJ+n6GpqtHkddrY2bIN/mYpikaL80lrmJzK2WeNEqZS1nua1xOfVvgRDxqIwQGc/aPiLi9Xk9dxyKZ+jveu5KcMlEHOMqjoGRJSTFm4n5N2HEwg+ThMyL+f1/oEUxW0GKFa48m9gnKjBesMSzU/iGIdPZDyLKFZecyM0JPyABih4TGpS7pf7YnNutcAUD7EoWmApvzkpAFsOZPnYcWGWFyVD2dexHItATomDQOEZBJHN3CGvphTHGX7OJp5Km99TZIb8Ty2HxT1j8l8qFcHohbTceZZ4W6CaJqob+qbfitxXdHLdnt+pe+y6fpr4vNvks7sJf0IpwOdSyIVeQrcKKi1P8FhDQQe1+i6ETwrDnDYOUTPswqp4+3WOpe8V27yILFOdIDYTFzHuriSaZI/Rgiv3N8FEtQ87JMyNgF21/R0ZWCeJSHu44MLYm/tv55430+SVvS6sbKQC6YOJxsIc0eip+9CDnutedqu479ERsRppdtit1tlKey4sQyg//uNm3w7rx2omqq5T+W6AJIFSuifGjBPNNM2XWD61KHkyEF3B5pFJrLL3gKTwvOO6JOs4fiI7eqWtqKERfDXwDGzA1zgZboTyLPw0QeEuMwwxjKuWch2TfYWtZXFxoM1U4/W+wzeOc+wxS3bIX9f+WjwWSdBy7YxHA5PeU/LWIOIsJDliBUJOjsA==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque

